// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;
import 'package:flutter_dotenv/flutter_dotenv.dart' show dotenv;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static FirebaseOptions get android => FirebaseOptions(
    apiKey: _requiredEnv('FIREBASE_ANDROID_API_KEY'),
    appId: _requiredEnv('FIREBASE_ANDROID_APP_ID'),
    messagingSenderId: _requiredEnv('FIREBASE_MESSAGING_SENDER_ID'),
    projectId: _requiredEnv('FIREBASE_PROJECT_ID'),
    storageBucket: _requiredEnv('FIREBASE_STORAGE_BUCKET'),
  );

  static FirebaseOptions get ios => FirebaseOptions(
    apiKey: _requiredEnv('FIREBASE_IOS_API_KEY'),
    appId: _requiredEnv('FIREBASE_IOS_APP_ID'),
    messagingSenderId: _requiredEnv('FIREBASE_MESSAGING_SENDER_ID'),
    projectId: _requiredEnv('FIREBASE_PROJECT_ID'),
    storageBucket: _requiredEnv('FIREBASE_STORAGE_BUCKET'),
    iosBundleId: _requiredEnv('FIREBASE_IOS_BUNDLE_ID'),
  );
}

String _requiredEnv(String key) {
  final value = dotenv.env[key];
  if (value == null || value.isEmpty) {
    throw StateError('Missing required Firebase config value: $key');
  }
  return value;
}
